name: Jest-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
          node-version: [15.x]

    steps:

      - uses: actions/checkout@v2


      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup_node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
        
        env:
          CI: true
        
      - name: test and code coverage
        run: npm test
        


